# Generated by Django 4.0.6 on 2022-10-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_customerrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_phonenumber',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
