# Generated by Django 4.0.6 on 2022-12-20 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0002_alter_company_options_bill_sold_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_medicines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Requested on'),
        ),
    ]
