# Generated by Django 4.0.1 on 2022-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_companybank_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medical_type',
            field=models.CharField(choices=[('T', 'Tablet'), ('S', 'Syrup')], max_length=1),
        ),
    ]
