# Generated by Django 4.0.1 on 2022-02-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_medicine_medical_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1),
        ),
    ]
