# Generated by Django 4.0.6 on 2022-10-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_remove_bill_customer_bill_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='billdetails',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medicine.bill'),
        ),
    ]
