# Generated by Django 4.0.1 on 2022-02-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_alter_employeesalary_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_no',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmployeeBank',
        ),
    ]
