# Generated by Django 4.0.1 on 2022-02-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_employee_bank_account_no_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='prescription',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Has request been granted?'),
        ),
    ]
