# Generated by Django 4.0.1 on 2022-03-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_alter_customerrequest_prescription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerrequest',
            options={'ordering': ['-added_on']},
        ),
        migrations.AddField(
            model_name='medicine',
            name='salt_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='salt_quantity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MedicalDetails',
        ),
    ]
