# Generated by Django 4.0.1 on 2022-03-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_alter_customerrequest_options_medicine_salt_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybank',
            old_name='ifsc_no',
            new_name='bank_name',
        ),
    ]
